baseURL = "https://www.stepbystep.cf/"
theme = "stack"
languageCode = "zh-cn"
[markup.goldmark.renderer]
unsafe = true

disqusShortname = "hugo-theme-stack"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

[languages.zh-cn]
languageName = "中文"
title = "一步一个脚印"
weight = 1

[languages.en]
languageName = "English"
title = "Step by step"
weight = 2
